return {
  border = 'rounded',
  colorscheme = 'tokyonight',
  background = 'dark',
  transparent = true,
  log_level = vim.log.levels.OFF,
  fidget = false,
  finder = 'fzf-lua',
  gitlinker = true,
  indent_blankline = true,
  lsp_progress = true,
  sleuth = false,
  which_key = false,
  yanky = true,
}
