gui:
  expandFocusedSidePanel: true
  sidePanelWidth: 0.25
  filterMode: fuzzy
  border: single
  theme:
    selectedLineBgColor:
      - reverse
    selectedRangeBgColor:
      - reverse
git:
  pagers:
    - colorArg: always
      pager: diff-so-fancy
  branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --date=iso --pretty=medium --oneline {{branchName}} --"
  autoStageResolvedConflicts: false
  allBranchesLogCmds:
    - git log --graph --all --color=always --abbrev-commit --decorate --date=iso  --pretty=medium --oneline
notARepository: "quit" # one of: 'prompt' | 'create' | 'skip' | 'quit'
