# format = """
# $directory\
# $git_branch\
# $git_status\
# $sudo\
# $fill\
# $cmd_duration $jobs $time\
# $line_break\
# $character"""

format = """
[┌─ ](bold cyan)$directory$git_branch$git_status$sudo$fill $cmd_duration$jobs$time
[└](bold cyan)$character"""

add_newline = false

[directory]
read_only = " ro"

[git_branch]
symbol = ""

[git_status]
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"

[sudo]
symbol = "su "

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"
vicmd_symbol = "[<](bold green)"

[fill]
style = "bold cyan"
symbol = "─"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[jobs]
style = "bold red"
symbol = "j "

[time]
disabled = false
format = "[$time]($style)"
style = "bold white"
