add_newline = false

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$sudo\
$line_break\
$status\
$character"""

[directory]
read_only = " ro"
truncate_to_repo = false

[git_branch]
symbol = ""

[git_status]
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"

[character]
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"
vicmd_symbol = "[<](bold green)"
